var englishP = [
{"phon":"[hæv ə fəˈmɪliə rɪŋ]","title":"Have a familiar ring","descr":"Звучать знакомо"},
{"phon":"[ðə kɑːdz ɑː stækt əˈgɛnst ˈsʌmθɪŋ]","title":"The cards are stacked against something","descr":"Расклад не в пользу чего-либо"},
{"phon":"[rɪŋ ə bɛl]","title":"Ring a bell","descr":"Казаться знакомым"},
{"phon":"[pʊl wʌnz ˈfɪŋgər aʊt]","title":"Pull one’s finger out","descr":"Перестать бездельничать и приняться за работу"},
{"phon":"[pʊt tuː ænd tuː təˈgɛðə]","title":"Put two and two together","descr":"Сложить два плюс два"},
{"phon":"[wɒt biːts mi]","title":"What beats me…","descr":"Чего я не могу понять…"},
{"phon":"[aʊt ɒv tʌʧ]","title":"Out of touch","descr":"Не в курсе"},
{"phon":"[gɛt ðə rɒŋ ɛnd ɒv ðə stɪk]","title":"Get the wrong end of the stick","descr":"Неверно понять"},
{"phon":"[pʊt ɪt daʊn tuː ɪksˈpɪərɪəns]","title":"Put it down to experience","descr":"Отрицательный опыт - это тоже опыт"},
{"phon":"[dəʊnt hæv ə klu]","title":"Don’t have a clue","descr":"Понятия не имею"},
{"phon":"[gɪv fuːd fɔː θɔːt]","title":"Give food for thought","descr":"Давать пищу для размышлений"},
{"phon":"[lɜːn wʌnz ˈlɛsn]","title":"Learn one’s lesson","descr":"Усвоить свой урок"},
{"phon":"[pʊt ðə ˈrɛkɔːd streɪt]","title":"Put the record straight","descr":"Прояснить ситуацию"},
{"phon":"[hæv ˈsɛkənd θɔːts]","title":"Have second thoughts","descr":"Передумать, засомневаться"},
{"phon":"[gəʊst ɒv ə ʧɑːns]","title":"Ghost of a chance","descr":"Призрачный шанс"},
{"phon":"[rʌn laɪk ə driːm]","title":"Run like a dream","descr":"Идти как по маслу"},
{"phon":"[wɜːk laɪk ˈmæʤɪk]","title":"Work like magic","descr":"Творить чудеса"},
{"phon":"[duː ðə trɪk ]","title":"Do the trick","descr":"Добиться цели"},
{"phon":"[hɪt ðə bɪg taɪm]","title":"Hit the big time","descr":"Поймать удачу за хвост"},
{"phon":"[əˈgɛnst ɔːl ði ɒdz]","title":"Against all the odds","descr":"Вопреки всем ожиданиям"},
{"phon":"[teɪk fɔː ˈgrɑːntɪd]","title":"Take for granted","descr":"Принимать на веру"},
{"phon":"[fɔːˈgɒn kənˈkluːʒən]","title":"Foregone conclusion","descr":"Предрешённый исход"},
{"phon":"[ˈtʌʧənˈgəʊ]","title":"Touch-and-go","descr":"Крайне неуверенный в исходе чего-то"},
{"phon":"[nəʊ ˈpraɪzɪz fɔː ˈgɛsɪŋ]","title":"No prizes for guessing","descr":"Несложно догадаться"},
{"phon":"[dəʊnt pʊʃ jɔː lʌk]","title":"Don’t push your luck","descr":"Не искушай свою судьбу"},
{"phon":"[gɪv wʌnz ɔːl]","title":"Give one’s all","descr":"Отдавать все свои силы"},
{"phon":"[gəʊ ɔːl aʊt]","title":"Go all out","descr":"Выкладываться по полной"},
{"phon":"[æt ə pʊʃ]","title":"At a push","descr":"Если приложить дополнительное усилие"},
{"phon":"[hæv ə gəʊ]","title":"Have a go","descr":"Попробовать, предпринять попытку"},
{"phon":"[gəʊ θruː ðə ˈməʊʃənz]","title":"Go through the motions","descr":"Делать что-либо для галочки"}
];