var franchP = [
{"phon":"[kwa de nœf?]","descr":"Что нового?","title":"Quoi de neuf?"},
{"phon":"[sa fɛ lɔ̃tɑ̃.]","descr":"Давно не виделись","title":"Ça fait longtemps"},
{"phon":"[ɑ̃ʃɑ̃te]","descr":"Приятно познакомиться","title":"Enchanté(e)"},
{"phon":"[ɛkskyze-mwa]","descr":"Извините меня","title":"Excusez-moi"},
{"phon":"[Bon appétit]","descr":"Приятного аппетита!","title":"Bon appétit!"}, 
{"phon":"[je sɥi dezɔle]","descr":"Мне жаль. Простите","title":"Je suis désolé(e)"},
{"phon":"[mɛʁsi boku]","descr":"Спасибо большое","title":"Merci beaucoup"},
{"phon":"[bjɛ̃vəny]","descr":"Добро пожаловать!","title":"Bienvenue!"},
{"phon":"[de ʁjɛ̃]","descr":"Не за что! (в ответ на благодарность)","title":"De rien!"},
{"phon":"[paʁle-vu ʁys]","descr":"Вы говорите по-русски?","title":"Parlez-vous russe?"},
{"phon":"[paʁle-vu ɑ̃ɡlɛ]","descr":"Вы говорите по-английски?","title":"Parlez-vous anglais?"},
{"phon":"[kɔm diʁ sa ɑ̃ fʁɑ̃sɛ]","descr":"Как это будет по-французски?","title":"Comment dire ça en français?"},
{"phon":"[je n sɛ pa]","descr":"Я не знаю","title":"Je ne sais pas"},
{"phon":"[je paʁl fʁɑ̃sɛ ɛ̃ pəti pø]","descr":"Я немного говорю по-французски","title":"Je parle français un petit peu"},
{"phon":"[S’il vous plaît]","descr":"Пожалуйста (Просьба)","title":"S’il vous plaît"},
{"phon":"[vu ɛm'ɑ̃tɑ̃de]","descr":"Вы меня слышите?","title":"Vous m'entendez?"},
{"phon":"[ty ekut kɛl stil de myzik]","descr":"Какую музыку ты слушаешь?","title":"Tu écoute quel style de musique?"},
{"phon":"[bɔ̃swaʁ]","descr":"Добрый вечер!","title":"Bonsoir!"},
{"phon":"[Bon matin]","descr":"Доброе утро!","title":"Bon matin!"},
{"phon":"[bɔ̃ʒuʁ]","descr":"Здравствуйте!","title":"Bonjour!"},
{"phon":"[saly]","descr":"Привет!","title":"Salut!"},
{"phon":"[kɔm sa va]","descr":"Как у тебя дела?","title":"Comment ça va?"},
{"phon":"[kɔm ale-vu]","descr":"Как вы поживаете?","title":"Comment allez-vous?"},
{"phon":"[sa va bjɛ̃, mɛʁsi]","descr":"Все хорошо, спасибо","title":"Ça va bien, merci"},
{"phon":"[Comment ça va vɔtʁ famij]","descr":"Как поживает ваша семья?","title":"Comment ça va votre famille?"},
{"phon":"[je dwa i ale]","descr":"Мне нужно идти","title":"Je dois y aller"},
{"phon":"[o rəvwaʁ]","descr":"До свидания","title":"Au revoir"},
{"phon":"[kə fɛt-vu]","descr":"Чем вы занимаетесь? (по жизни)","title":"Que faites-vous?"},
{"phon":"[ɛ-s kə vu puve ɛl’ekʁiʁ]","descr":"Можете это записать?","title":"Est-ce que vous pouvez l’écrire?"},
{"phon":"[je n kɔ̃pʁɑ̃ pas]","descr":"Я не понимаю","title":"Je ne comprends pas"},
{"phon":"[Vous êtes occupé maintenant mɛ̃tnɑ̃]","descr":"Вы сейчас заняты?","title":"Vous êtes occupé maintenant?"},
{"phon":"[ʒi'ɛm]","descr":"Я люблю...","title":"J'aime ..."}
];