var germanP = [
{"phon":"[zɪç ˈapˌmyːən viː deːɐ̯ fɪʃ aʊ̯f dəm ˈtʁɔknən]","title":"Sich abmühen wie der Fisch auf dem Trocknen","descr":"Биться как рыба об лед"},
{"phon":"[da liːkt deːɐ̯ ˈhaːzə ɪm ˈpfɛfɐ]","title":"Da liegt der Hase im Pfeffer!","descr":"Вот, где собака зарыта!"},
{"phon":"[ˈaɪ̯nən bärenhunger ˈhaːbn̩]","title":"Einen Bärenhunger haben","descr":"Быть голодным как волк"},
{"phon":"[vɛn diː ˈhʊndə mɪt dəm ʃvanʦ mɪt dəm ʃvanʦ]","title":"Wenn die Hunde mit dem Schwanz bellen","descr":"Когда рак на горе свистнет"},
{"phon":"[schlafende ˈhʊndə zɔl man nɪçt ˈvɛkn̩]","title":"Schlafende Hunde soll man nicht wecken","descr":"Не буди лихо, пока оно тихо"},
{"phon":"[aɪ̯n ˈaltɐ ˈhaːzə]","title":"Ein alter Hase","descr":"Стреляный воробей"},
{"phon":"[das zɪnt nuːɐ̯ ˈklaɪ̯nə ˈfɪʃə]","title":"Das sind nur kleine Fische","descr":"Используйте это выражение, если хотите сказать, что проблемы не такие уж и большие"},
{"phon":"[fyːɐ̯ jemanden diː fyːɐ̯ jemanden diː ˈleːɡn̩]","title":"Für jemanden die Hand ins Feuer legen","descr":"Давать голову на отсечение за кого-либо"},
{"phon":"[mɪt den völfen ˈhɔɪ̯lən]","title":"Mit den Wölfen heulen","descr":"Присоединяться к общему мнению"},
{"phon":"[ˈblaʊ̯ɐ ˈmoːntaːk]","title":"Blauer Montag", "descr":"Понедельник - день тяжелый"},
{"phon":"[ɪç ˈɡlaʊ̯bə, maɪ̯n, maɪ̯n ʃvaɪ̯n pfeift]","title":"Ich glaube, mein Schwein pfeift","descr":"Я возмущен"},
{"phon":"[viː diː ˈkaʦə den ˈhaɪ̯sn̩ bʁaɪ̯ ˈɡeːən]","title":"Wie die Katze um den heißen Brei gehen","descr":"Ходить вокруг да около"},
{"phon":"[jemandem ˈɛtvas aʊ̯f diː ˈnaːzə ˈbɪndn̩]","title":"Jemandem etwas auf die Nase binden","descr":"Вешать лапшу на уши"},
{"phon":"[jemandem aʊ̯f den ʦaːn fʊ̯̈lən]","title":"Jemandem auf den Zahn fühlen","descr":"Выведать что-либо у кого-либо"},
{"phon":"[aʊ̯f dəm ˈʦaːnflaɪ̯ʃ ˈɡeːən]","title":"Auf dem Zahnfleisch gehen","descr":"Смертельно устать"},
{"phon":"[aʊ̯f dəm ˈʦaːnflaɪ̯ʃ ˈkʁiːçn̩]","title":"Auf dem Zahnfleisch kriechen","descr":"Тянуть из последних сил"},
{"phon":"[mit einem blauen ˈaʊ̯ɡə daˈfɔnkɔmən]","title":"Mit einem blauen Auge davonkommen","descr":"Легко отделаться"},
{"phon":"[fɔn deːɐ̯ hant ɪn den mʊnt ˈleːbn̩]","title":"Von der Hand in den Mund leben","descr":"Едва сводить концы с концами"},
{"phon":"[kaɪ̯n blat foːɐ̯ den mʊnt ˈneːmən]","title":"Kein Blatt vor den Mund nehmen","descr":"Говорить без обиняков"},
{"phon":"[jemandem mɪt ˈɛtvas ɪn den ohren ˈliːɡn̩]","title":"Jemandem mit etwas in den Ohren liegen","descr":"Прожужжать все уши"},
{"phon":"[aʊ̯s deːɐ̯ haʊ̯t ˈfaːʁən]","title":"Aus der Haut fahren","descr":"Выйти из себя, потерять самообладание"},
{"phon":"[zɪç ˈɛtvas ˈhɪntɐ diː ohren ˈʃʁaɪ̯bn̩]","title":"Sich etwas hinter die Ohren schreiben","descr":"Зарубить на носу"},
{"phon":"[zɪç aufs oːɐ̯ ˈhaʊ̯ən]","title":"Sich aufs Ohr hauen","descr":"Отправиться на боковую"},
{"phon":"[jemanden aʊ̯f den Arm nehmen]","title":"Jemanden auf den Arm nehmen","descr":"Ёрничать"},
{"phon":"[jemandem diː ˈdaʊ̯mən ˈdʁʏkn̩]","title":"Jemandem die Daumen drücken","descr":"Держать за кого-то кулаки"},
{"phon":"[diː ˈnaːzə fɔl]","title":"Die Nase voll haben","descr":"быть сытым по горло"},
{"phon":"[ˈkaltə ˈfyːsə bəˈkɔmən]","title":"Kalte Füße bekommen","descr":"Испугаться"},
{"phon":"[jemanden mɪt dəm ˈʁʏkn̩ ˈanˌʃaʊ̯ən]","title":"Jemanden mit dem Rücken anschauen","descr":"Игнорировать кого-либо"},
{"phon":"[aɪ̯n bʁɛt foːɐ̯ dəm kɔpf ˈhaːbn̩]","title":"Ein Brett vor dem Kopf haben","descr":"Туго соображать"},
{"phon":"[mɪt dəm kɔpf dʊʁç diː vant]","title":"Mit dem Kopf durch die Wand","descr":"Идти напролом"},
{"phon":"[ɪç den mʊnt fɛɐ̯ˈbʁɛnən]","title":"Sich den Mund verbrennen","descr":"Сболтнуть лишнего (себе во вред)"},
{"phon":"[viː aʊ̯f ˈaɪ̯ɐn ˈɡeːən]","title":"Wie auf Eiern gehen","descr":"Действовать крайне осторожно"},
{"phon":"[ɪn den sauren ˈapfl̩ ˈbaɪ̯sn̩]","title":"In den sauren Apfel beißen","descr":"Быть вынужденным взяться за неприятное дело"}
]